Add new logic to handle invisible rules.
forseti-security/forseti-security pull request #3829
Opened 2020-10-16 23:25 UTC by tiu1234

Thanks for opening a Pull Request!

Here's a handy checklist to ensure your PR goes smoothly.

- [ ] I signed Google's [Contributor License Agreement](https://opensource.google.com/docs/cla/)
- [ ] My code conforms to Google's [python style](https://google.github.io/styleguide/pyguide.html).
- [ ] My PR at a minimum doesn't decrease unit-test coverage (if applicable).
- [ ] My PR has been functionally tested.
- [ ] All of the [tests](https://forsetisecurity.org/docs/latest/develop/dev/testing.html) pass.
- [ ] I have submitted a corresponding PR for documentation in the `forsetisecurity.org-dev branch` and included this on this PR (if applicable).
- [ ] My documentation has been functionally tested and used (if applicable).
- [ ] I have submitted a corresponding PR in the [Forseti Terraform module](https://github.com/forseti-security/terraform-google-forseti) (if applicable).

These guidelines and more can be found in our [contributing guidelines](https://github.com/forseti-security/forseti-security/blob/dev/.github/CONTRIBUTING.md).

2020-10-17 01:01 UTC, gkowalski-google commented on google/cloud/forseti/enforcer/project_enforcer.py
> +                expected_rules.rules[rule]):
(nit) Please fix lint.

2020-10-17 01:01 UTC, gkowalski-google requested changes
Minor fix.

2020-10-19 19:26 UTC, tiu1234 commented on google/cloud/forseti/enforcer/project_enforcer.py
> +                expected_rules.rules[rule]):
what should i change here?

2020-10-19 20:59 UTC, tiu1234 commented
@googlebot I signed it!

2020-10-19 21:05 UTC, tiu1234 commented
@googlebot I signed it!

2020-10-19 21:06 UTC, gkowalski-google commented
/gcbrun

2020-10-20 16:22 UTC, gkowalski-google approved these changes
LGTM. The integration test for the enforcer passed, the only failure was for a CV test which has been flaky.

2020-10-20 16:22 UTC, merged